# Generated by Django 4.2.6 on 2023-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicpd',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fashionpd',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jewellerypd',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
    ]
