# Generated by Django 4.2.6 on 2023-11-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_electronicpd_image_alter_fashionpd_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManfashionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slag', models.SlugField(max_length=255, unique=models.CharField(max_length=255, unique=True))),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WomenfashionSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slag', models.SlugField(max_length=255, unique=models.CharField(max_length=255, unique=True))),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WomenfashionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slag', models.SlugField(max_length=255, unique=models.CharField(max_length=255, unique=True))),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.fashionpd')),
            ],
        ),
        migrations.CreateModel(
            name='ManfashionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slag', models.SlugField(max_length=255, unique=models.CharField(max_length=255, unique=True))),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.fashionpd')),
            ],
        ),
    ]
