# Generated by Django 4.2.6 on 2023-11-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_manfashionsubcategory_womenfashionsubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manfashioncategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meida/Manfashion'),
        ),
        migrations.AddField(
            model_name='manfashionsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meida/ManfashionSubCategory'),
        ),
        migrations.AddField(
            model_name='womenfashioncategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meida/WomenfashionCategory'),
        ),
        migrations.AddField(
            model_name='womenfashionsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meida/WomenfashionSubCategory'),
        ),
    ]
