# Generated by Django 4.2.6 on 2023-11-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_rename_electronicpdname_electronicpd_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computers',
            new_name='Computer',
        ),
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='EarRing',
        ),
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
        migrations.RenameModel(
            old_name='Rings',
            new_name='Mobile',
        ),
        migrations.RenameModel(
            old_name='EarRings',
            new_name='Ring',
        ),
        migrations.AlterField(
            model_name='earring',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.jewellerypd'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.electronicpd'),
        ),
    ]
