# Generated by Django 4.2.6 on 2023-11-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_rename_computers_computer_rename_mobiles_earring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manfashionsubcategory',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.fashionpd'),
        ),
    ]
