# Generated by Django 4.2.7 on 2023-11-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_customer_electronicproduct_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catigories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug_name', models.SlugField(max_length=255, null=True, unique=models.CharField(max_length=255, null=True))),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manfashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Manfashion')),
                ('catigory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories')),
            ],
        ),
        migrations.CreateModel(
            name='ManfashionBestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ManfashionSubCategory')),
                ('catigory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories')),
            ],
        ),
        migrations.CreateModel(
            name='Womenfashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='WomenfashionCategory')),
                ('catigory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories')),
            ],
        ),
        migrations.CreateModel(
            name='WomenfashionBestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='WomenfashionSubCategory')),
                ('catigory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories')),
            ],
        ),
        migrations.RemoveField(
            model_name='manfashioncategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='manfashionsubcategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='womenfashioncategory',
            name='price',
        ),
        migrations.DeleteModel(
            name='WomenfashionSubCategory',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='earring',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='neklace',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='slag',
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='price',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='neklace',
            name='price',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='price',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ElectronicPd',
        ),
        migrations.DeleteModel(
            name='FashionPd',
        ),
        migrations.DeleteModel(
            name='JewelleryPd',
        ),
        migrations.DeleteModel(
            name='ManfashionCategory',
        ),
        migrations.DeleteModel(
            name='ManfashionSubCategory',
        ),
        migrations.DeleteModel(
            name='WomenfashionCategory',
        ),
        migrations.AddField(
            model_name='computer',
            name='catigory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories'),
        ),
        migrations.AddField(
            model_name='earring',
            name='catigory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='catigory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='catigory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories'),
        ),
        migrations.AddField(
            model_name='neklace',
            name='catigory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories'),
        ),
        migrations.AddField(
            model_name='ring',
            name='catigory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.catigories'),
        ),
    ]
